// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLQuanKaraokeHKT.Models;

#nullable disable

namespace QLQuanKaraokeHKT.Migrations
{
    [DbContext(typeof(QlkaraokeHktContext))]
    partial class QlkaraokeHktContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maCa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCa"));

                    b.Property<TimeOnly>("GioBatDauCa")
                        .HasColumnType("time")
                        .HasColumnName("gioBatDauCa");

                    b.Property<TimeOnly>("GioKetThucCa")
                        .HasColumnType("time")
                        .HasColumnName("gioKetThucCa");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenCa");

                    b.HasKey("MaCa")
                        .HasName("PK_CaLamViec");

                    b.ToTable("CaLamViec", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietHoaDonDichVu", b =>
                {
                    b.Property<int>("MaCthoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maCTHoaDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCthoaDon"));

                    b.Property<Guid>("MaHoaDon")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maHoaDon");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("maSanPham");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("soLuong");

                    b.HasKey("MaCthoaDon")
                        .HasName("PK__ChiTietH__22113E7CA9E09973");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietHoaDonDichVu", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietPhieuHuyHang", b =>
                {
                    b.Property<int>("MaChiTietPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maChiTietPhieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPhieu"));

                    b.Property<int>("MaPhieuHuyHang")
                        .HasColumnType("int")
                        .HasColumnName("maPhieuHuyHang");

                    b.Property<int>("MaVatLieu")
                        .HasColumnType("int")
                        .HasColumnName("maVatLieu");

                    b.Property<int>("SoLuongVatLieuHuy")
                        .HasColumnType("int")
                        .HasColumnName("soLuongVatLieuHuy");

                    b.HasKey("MaChiTietPhieu")
                        .HasName("PK__ChiTietP__D8405232CEEF559A");

                    b.HasIndex("MaPhieuHuyHang");

                    b.HasIndex("MaVatLieu");

                    b.ToTable("ChiTietPhieuHuyHang", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietPhieuKiemHang", b =>
                {
                    b.Property<int>("MaChiTietPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maChiTietPhieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPhieu"));

                    b.Property<int?>("ChenhLech")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("chenhLech")
                        .HasComputedColumnSql("([soLuongThucTe]-[soLuongTheoSo])", false);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ghiChu");

                    b.Property<int>("MaPhieuKiemHang")
                        .HasColumnType("int")
                        .HasColumnName("maPhieuKiemHang");

                    b.Property<int>("MaVatLieu")
                        .HasColumnType("int")
                        .HasColumnName("maVatLieu");

                    b.Property<int>("SoLuongTheoSo")
                        .HasColumnType("int")
                        .HasColumnName("soLuongTheoSo");

                    b.Property<int>("SoLuongThucTe")
                        .HasColumnType("int")
                        .HasColumnName("soLuongThucTe");

                    b.HasKey("MaChiTietPhieu")
                        .HasName("PK__ChiTietP__D8405232A82E4C91");

                    b.HasIndex("MaPhieuKiemHang");

                    b.HasIndex("MaVatLieu");

                    b.ToTable("ChiTietPhieuKiemHang", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietPhieuNhapHang", b =>
                {
                    b.Property<int>("MaChiTietPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maChiTietPhieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPhieu"));

                    b.Property<int>("MaPhieuNhapHang")
                        .HasColumnType("int")
                        .HasColumnName("maPhieuNhapHang");

                    b.Property<int>("MaVatLieu")
                        .HasColumnType("int")
                        .HasColumnName("maVatLieu");

                    b.Property<int>("SoLuongVatLieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("soLuongVatLieuNhap");

                    b.HasKey("MaChiTietPhieu")
                        .HasName("PK__ChiTietP__D8405232B9AC7D2C");

                    b.HasIndex("MaPhieuNhapHang");

                    b.HasIndex("MaVatLieu");

                    b.ToTable("ChiTietPhieuNhapHang", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.GiaDichVu", b =>
                {
                    b.Property<int>("MaGiaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGiaDichVu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("donGia");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("maSanPham");

                    b.Property<DateOnly>("NgayApDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ngayApDung")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HieuLuc")
                        .HasColumnName("trangThai");

                    b.HasKey("MaGiaDichVu")
                        .HasName("PK__GiaDichV__E5242F374B0CF2DF");

                    b.HasIndex(new[] { "MaSanPham", "NgayApDung" }, "IX_GiaDichVu_SanPham_NgayApDung");

                    b.ToTable("GiaDichVu", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.GiaVatLieu", b =>
                {
                    b.Property<int>("MaGiaVatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGiaVatLieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaVatLieu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("donGia");

                    b.Property<int>("MaVatLieu")
                        .HasColumnType("int")
                        .HasColumnName("maVatLieu");

                    b.Property<DateOnly>("NgayApDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ngayApDung")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HieuLuc")
                        .HasColumnName("trangThai");

                    b.HasKey("MaGiaVatLieu")
                        .HasName("PK__GiaVatLi__7CD9F14AF5AAD9C1");

                    b.HasIndex(new[] { "MaVatLieu", "NgayApDung" }, "IX_GiaVatLieu_VatLieu_NgayApDung");

                    b.ToTable("GiaVatLieu", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.HoaDonDichVu", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maHoaDon")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaKhachHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maKhachHang");

                    b.Property<string>("MoTaHoaDon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("moTaHoaDon");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenHoaDon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenHoaDon");

                    b.Property<decimal>("TongTienHoaDon")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("tongTienHoaDon");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChoThanhToan")
                        .HasColumnName("trangThai");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDonDi__026B4D9A25DB1AE2");

                    b.HasIndex(new[] { "MaKhachHang" }, "IX_HoaDon_KhachHang");

                    b.HasIndex(new[] { "NgayTao" }, "IX_HoaDon_NgayTao");

                    b.HasIndex(new[] { "TrangThai" }, "IX_HoaDon_TrangThai");

                    b.ToTable("HoaDonDichVu", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.KhachHang", b =>
                {
                    b.Property<Guid>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maKhachHang")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<Guid>("MaTaiKhoan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maTaiKhoan");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenKhachHang");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__0CCB3D497F337DE2");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "IX_KhachHang_TaiKhoan");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLichLamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maLichLamViec");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichLamViec"));

                    b.Property<int>("MaCa")
                        .HasColumnType("int")
                        .HasColumnName("maCa");

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNhanVien");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date")
                        .HasColumnName("ngayLamViec");

                    b.HasKey("MaLichLamViec")
                        .HasName("PK_LichLamViec");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichLamViec", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LichSuSuDungPhong", b =>
                {
                    b.Property<int>("IdLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLichSu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichSu"));

                    b.Property<Guid?>("MaHoaDon")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maHoaDon");

                    b.Property<Guid>("MaKhachHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maKhachHang");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("maPhong");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianBatDau");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianKetThuc");

                    b.HasKey("IdLichSu")
                        .HasName("PK__LichSuSu__C6FF38160F0FFDA4");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaPhong");

                    b.ToTable("LichSuSuDungPhong", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LoaiPhongHatKaraoke", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maLoaiPhong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<int>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("sucChua");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenLoaiPhong");

                    b.HasKey("MaLoaiPhong")
                        .HasName("PK__loaiPhon__106832AAF41DD649");

                    b.ToTable("loaiPhongHatKaraoke", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LuongCaLamViec", b =>
                {
                    b.Property<int>("MaLuongCaLamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuongCaLamViec"));

                    b.Property<decimal>("GiaCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayApDung")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.HasKey("MaLuongCaLamViec");

                    b.HasIndex("MaCa");

                    b.ToTable("LuongCaLamViec", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.MaOtp", b =>
                {
                    b.Property<int>("IdOtp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idOTP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOtp"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit")
                        .HasColumnName("daSuDung");

                    b.Property<Guid>("MaTaiKhoan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maTaiKhoan");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayHetHan");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("maOTP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("maOTP");

                    b.HasKey("IdOtp")
                        .HasName("PK__MaOTP__3CB844F21AE80C6C");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "IX_MaOTP_TaiKhoan");

                    b.ToTable("MaOTP", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.MonAn", b =>
                {
                    b.Property<int>("MaMonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maMonAn");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonAn"));

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("maSanPham");

                    b.Property<int>("SoLuongConLai")
                        .HasColumnType("int")
                        .HasColumnName("soLuongConLai");

                    b.HasKey("MaMonAn")
                        .HasName("PK__MonAn__2D20DD221681F916");

                    b.HasIndex("MaSanPham");

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maNhaCungCap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("diaChi");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenNhaCungCap");

                    b.HasKey("MaNhaCungCap")
                        .HasName("PK__NhaCungC__D0B4D6DE5A14D52C");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.NhanVien", b =>
                {
                    b.Property<Guid>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNV")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<string>("LoaiNhanVien")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loaiNhanVien");

                    b.Property<Guid>("MaTaiKhoan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maTaiKhoan");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("soDienThoai");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__7A3EC7D5D566A33A");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "IX_NhanVien_TaiKhoan");

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__AB6E61642A8F12D3")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuHuyHang", b =>
                {
                    b.Property<int>("MaPhieuHuyHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhieuHuyHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuHuyHang"));

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTaPhieu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("moTaPhieu");

                    b.Property<DateOnly>("NgayTaoPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ngayTaoPhieu")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<Guid>("NhanVienMaNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenPhieu");

                    b.Property<decimal>("TongTienThatThoat")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("tongTienThatThoat");

                    b.HasKey("MaPhieuHuyHang")
                        .HasName("PK__PhieuHuy__33F1711020CBF93C");

                    b.HasIndex("NhanVienMaNv");

                    b.ToTable("PhieuHuyHang", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuKiemHang", b =>
                {
                    b.Property<int>("MaPhieuKiemHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhieuKiemHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuKiemHang"));

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTaPhieu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("moTaPhieu");

                    b.Property<DateOnly>("NgayKiemKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ngayKiemKe")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<Guid>("NhanVienMaNv")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaPhieuKiemHang")
                        .HasName("PK__PhieuKie__483B07F2550A1DF0");

                    b.HasIndex("NhanVienMaNv");

                    b.ToTable("PhieuKiemHang", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuLuong", b =>
                {
                    b.Property<int>("MaPhieuLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhieuLuong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuLuong"));

                    b.Property<decimal>("HeSoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("heSoLuong");

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNhanVien");

                    b.Property<DateOnly>("NgayIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ngayIn")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<decimal>("TongTienLuong")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("tongTienLuong");

                    b.HasKey("MaPhieuLuong")
                        .HasName("PK__PhieuLuo__8D6F261279E4BA60");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuLuong", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuNhapHang", b =>
                {
                    b.Property<int>("MaPhieuNhapHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhieuNhapHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhapHang"));

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int")
                        .HasColumnName("maNhaCungCap");

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTaPhieu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("moTaPhieu");

                    b.Property<DateOnly>("NgayTaoPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ngayTaoPhieu")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<Guid>("NhanVienMaNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenPhieu");

                    b.Property<decimal>("TongTienNhap")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("tongTienNhap");

                    b.HasKey("MaPhieuNhapHang")
                        .HasName("PK__PhieuNha__E3AF626E6E25EC46");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("NhanVienMaNv");

                    b.ToTable("PhieuNhapHang", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhongHatKaraoke", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit")
                        .HasColumnName("dangSuDung");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int")
                        .HasColumnName("maLoaiPhong");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("maSanPham");

                    b.HasKey("MaPhong")
                        .HasName("PK__PhongHat__4CD55E1057E1C2E4");

                    b.HasIndex("MaLoaiPhong");

                    b.HasIndex("MaSanPham");

                    b.ToTable("PhongHatKaraoke", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refreshTokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<string>("ChuoiRefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("chuoiRefreshToken");

                    b.Property<Guid>("MaTaiKhoan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maTaiKhoan");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianHetHan");

                    b.Property<DateTime>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianTao")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RefreshTokenId")
                        .HasName("PK__RefreshT__FEAC95282D4E28E7");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "IX_RefreshToken_TaiKhoan");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.SanPhamDichVu", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maSanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("HinhAnhSanPham")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("hinhAnhSanPham");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenSanPham");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPhamD__5B439C439A4B08B7");

                    b.ToTable("SanPhamDichVu", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maTaiKhoan");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("tenDangNhap");

                    b.Property<bool>("daBiKhoa")
                        .HasColumnType("bit")
                        .HasColumnName("daBiKhoa");

                    b.Property<bool>("daKichHoat")
                        .HasColumnType("bit")
                        .HasColumnName("daKichHoat");

                    b.Property<string>("loaiTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loaiTaiKhoan");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ThuePhong", b =>
                {
                    b.Property<Guid>("MaThuePhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maThuePhong")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaKhachHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maKhachHang");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("maPhong");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianBatDau");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianKetThuc");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangSuDung")
                        .HasColumnName("trangThai");

                    b.HasKey("MaThuePhong")
                        .HasName("PK__ThuePhon__99717FBF068C52BC");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex(new[] { "MaPhong" }, "IX_ThuePhong_Phong");

                    b.HasIndex(new[] { "TrangThai" }, "IX_ThuePhong_TrangThai");

                    b.ToTable("ThuePhong", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.VaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("moTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.VatLieu", b =>
                {
                    b.Property<int>("MaVatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maVatLieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVatLieu"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("donViTinh");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("int")
                        .HasColumnName("soLuongTonKho");

                    b.Property<string>("TenVatLieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenVatLieu");

                    b.HasKey("MaVatLieu")
                        .HasName("PK__VatLieu__1B9590FA537F995B");

                    b.ToTable("VatLieu", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietHoaDonDichVu", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.HoaDonDichVu", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDonDichVus")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__maHoa__3D2915A8");

                    b.HasOne("QLQuanKaraokeHKT.Models.SanPhamDichVu", "MaSanPhamNavigation")
                        .WithMany("ChiTietHoaDonDichVus")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__maSan__3E1D39E1");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietPhieuHuyHang", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.PhieuHuyHang", "MaPhieuHuyHangNavigation")
                        .WithMany("ChiTietPhieuHuyHangs")
                        .HasForeignKey("MaPhieuHuyHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maPhi__690797E6");

                    b.HasOne("QLQuanKaraokeHKT.Models.VatLieu", "MaVatLieuNavigation")
                        .WithMany("ChiTietPhieuHuyHangs")
                        .HasForeignKey("MaVatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maVat__69FBBC1F");

                    b.Navigation("MaPhieuHuyHangNavigation");

                    b.Navigation("MaVatLieuNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietPhieuKiemHang", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.PhieuKiemHang", "MaPhieuKiemHangNavigation")
                        .WithMany("ChiTietPhieuKiemHangs")
                        .HasForeignKey("MaPhieuKiemHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maPhi__719CDDE7");

                    b.HasOne("QLQuanKaraokeHKT.Models.VatLieu", "MaVatLieuNavigation")
                        .WithMany("ChiTietPhieuKiemHangs")
                        .HasForeignKey("MaVatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maVat__72910220");

                    b.Navigation("MaPhieuKiemHangNavigation");

                    b.Navigation("MaVatLieuNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ChiTietPhieuNhapHang", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.PhieuNhapHang", "MaPhieuNhapHangNavigation")
                        .WithMany("ChiTietPhieuNhapHangs")
                        .HasForeignKey("MaPhieuNhapHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maPhi__607251E5");

                    b.HasOne("QLQuanKaraokeHKT.Models.VatLieu", "MaVatLieuNavigation")
                        .WithMany("ChiTietPhieuNhapHangs")
                        .HasForeignKey("MaVatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__maVat__6166761E");

                    b.Navigation("MaPhieuNhapHangNavigation");

                    b.Navigation("MaVatLieuNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.GiaDichVu", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.SanPhamDichVu", "MaSanPhamNavigation")
                        .WithMany("GiaDichVus")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__GiaDichVu__maSan__30C33EC3");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.GiaVatLieu", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.VatLieu", "MaVatLieuNavigation")
                        .WithMany("GiaVatLieus")
                        .HasForeignKey("MaVatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__GiaVatLie__maVat__57DD0BE4");

                    b.Navigation("MaVatLieuNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.HoaDonDichVu", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("HoaDonDichVus")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonDic__maKha__3864608B");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.KhachHang", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK__KhachHang__maTai__123EB7A3");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LichLamViec", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.CaLamViec", "CaLamViec")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("MaCa")
                        .IsRequired();

                    b.HasOne("QLQuanKaraokeHKT.Models.NhanVien", "NhanVien")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LichSuSuDungPhong", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.HoaDonDichVu", "MaHoaDonNavigation")
                        .WithMany("LichSuSuDungPhongs")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK__LichSuSuD__maHoa__4A8310C6");

                    b.HasOne("QLQuanKaraokeHKT.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("LichSuSuDungPhongs")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuSuD__maKha__498EEC8D");

                    b.HasOne("QLQuanKaraokeHKT.Models.PhongHatKaraoke", "MaPhongNavigation")
                        .WithMany("LichSuSuDungPhongs")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuSuD__maPho__489AC854");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LuongCaLamViec", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.CaLamViec", "CaLamViec")
                        .WithMany("LuongCaLamViecs")
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLamViec");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.MaOtp", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("MaOtps")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MaOTP__maTaiKhoa__08B54D69");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.MonAn", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.SanPhamDichVu", "MaSanPhamNavigation")
                        .WithMany("MonAns")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__MonAn__maSanPham__22751F6C");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.NhanVien", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK__NhanVien__maTaiK__0E6E26BF");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuHuyHang", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuHuyHangs")
                        .HasForeignKey("NhanVienMaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuKiemHang", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuKiemHangs")
                        .HasForeignKey("NhanVienMaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuLuong", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("PhieuLuongs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuLuon__maNha__17F790F9");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuNhapHang", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("PhieuNhapHangs")
                        .HasForeignKey("MaNhaCungCap")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuNhap__maNha__5CA1C101");

                    b.HasOne("QLQuanKaraokeHKT.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuNhapHangs")
                        .HasForeignKey("NhanVienMaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNhaCungCapNavigation");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhongHatKaraoke", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.LoaiPhongHatKaraoke", "MaLoaiPhongNavigation")
                        .WithMany("PhongHatKaraokes")
                        .HasForeignKey("MaLoaiPhong")
                        .IsRequired()
                        .HasConstraintName("FK__PhongHatK__maLoa__2A164134");

                    b.HasOne("QLQuanKaraokeHKT.Models.SanPhamDichVu", "MaSanPhamNavigation")
                        .WithMany("PhongHatKaraokes")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__PhongHatK__maSan__29221CFB");

                    b.Navigation("MaLoaiPhongNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.RefreshToken", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RefreshTo__maTai__03F0984C");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.ThuePhong", b =>
                {
                    b.HasOne("QLQuanKaraokeHKT.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("ThuePhongs")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__ThuePhong__maKha__44CA3770");

                    b.HasOne("QLQuanKaraokeHKT.Models.PhongHatKaraoke", "MaPhongNavigation")
                        .WithMany("ThuePhongs")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK__ThuePhong__maPho__43D61337");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.CaLamViec", b =>
                {
                    b.Navigation("LichLamViecs");

                    b.Navigation("LuongCaLamViecs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.HoaDonDichVu", b =>
                {
                    b.Navigation("ChiTietHoaDonDichVus");

                    b.Navigation("LichSuSuDungPhongs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDonDichVus");

                    b.Navigation("LichSuSuDungPhongs");

                    b.Navigation("ThuePhongs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.LoaiPhongHatKaraoke", b =>
                {
                    b.Navigation("PhongHatKaraokes");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhapHangs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.NhanVien", b =>
                {
                    b.Navigation("LichLamViecs");

                    b.Navigation("PhieuHuyHangs");

                    b.Navigation("PhieuKiemHangs");

                    b.Navigation("PhieuLuongs");

                    b.Navigation("PhieuNhapHangs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuHuyHang", b =>
                {
                    b.Navigation("ChiTietPhieuHuyHangs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuKiemHang", b =>
                {
                    b.Navigation("ChiTietPhieuKiemHangs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhieuNhapHang", b =>
                {
                    b.Navigation("ChiTietPhieuNhapHangs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.PhongHatKaraoke", b =>
                {
                    b.Navigation("LichSuSuDungPhongs");

                    b.Navigation("ThuePhongs");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.SanPhamDichVu", b =>
                {
                    b.Navigation("ChiTietHoaDonDichVus");

                    b.Navigation("GiaDichVus");

                    b.Navigation("MonAns");

                    b.Navigation("PhongHatKaraokes");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("MaOtps");

                    b.Navigation("NhanViens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("QLQuanKaraokeHKT.Models.VatLieu", b =>
                {
                    b.Navigation("ChiTietPhieuHuyHangs");

                    b.Navigation("ChiTietPhieuKiemHangs");

                    b.Navigation("ChiTietPhieuNhapHangs");

                    b.Navigation("GiaVatLieus");
                });
#pragma warning restore 612, 618
        }
    }
}
